"""Property-based state-machine tests for emit_batch.

Verifies the three public contracts in isolation:

1. Idempotency — re-emitting the same delivery_id is a counted no-op.
2. Doorbell contract — ring() fires exactly once per batch iff inserted > 0.
3. Atomicity — a mid-batch exception discards the whole transaction and
   leaves the model state (and DB row count) unchanged.
"""

from __future__ import annotations

import contextlib
import sqlite3
import time
from pathlib import Path
from typing import Any
from unittest.mock import patch

from hypothesis import HealthCheck, settings
from hypothesis import strategies as st
from hypothesis.stateful import Bundle, RuleBasedStateMachine, consumes, initialize, invariant, rule

from waitbus import _db
from waitbus._emit import emit_batch
from waitbus._types import EventInsert
from waitbus.sources._registry import known_sources

# ---------------------------------------------------------------------------
# Strategy helpers
# ---------------------------------------------------------------------------

_SOURCES = st.sampled_from(list(known_sources()))
_EVENT_TYPES = st.sampled_from(["workflow_run", "workflow_job", "prometheus_alert", "prometheus_watchdog"])
_INGEST_METHODS = st.sampled_from(["webhook", "poll", "manual", "fs"])

_RECEIVED_AT_NS = st.integers(
    min_value=1_000_000_000_000_000_001,  # above NS_RECEIVED_AT_MIN + 1
    max_value=int(time.time() * 1_000_000_000) + 10 * 365 * 24 * 3600 * 1_000_000_000,
)


def event_insert_strategy() -> st.SearchStrategy[EventInsert]:
    """Draw a fully valid EventInsert with a random delivery_id."""
    return st.builds(
        EventInsert,
        delivery_id=st.uuids().map(str),
        source=_SOURCES,
        event_type=_EVENT_TYPES,
        owner=st.from_regex(r"[a-z][a-z0-9-]{0,10}", fullmatch=True),
        repo=st.from_regex(r"[a-z][a-z0-9-]{0,10}", fullmatch=True),
        received_at=_RECEIVED_AT_NS,
        payload_json=st.just('{"k":"v"}'),
        ingest_method=_INGEST_METHODS,
    )


# ---------------------------------------------------------------------------
# State machine
# ---------------------------------------------------------------------------


class EmitBatchMachine(RuleBasedStateMachine):
    """Model-based state machine for emit_batch correctness.

    Model state mirrors what the real DB must contain:
    - ``seen_delivery_ids``: set of delivery_ids actually committed so far.
    - ``ring_count``: expected cumulative doorbell ring count.
    """

    pending: Bundle[EventInsert] = Bundle("pending")

    # ------------------------------------------------------------------
    # Initialisation
    # ------------------------------------------------------------------

    @initialize()
    def setup(self) -> None:
        # Temp DB — created fresh for each test case generated by Hypothesis.
        import tempfile

        self._tmpdir = tempfile.mkdtemp()
        self._db_path: Path = Path(self._tmpdir) / "events.db"
        _db.ensure_schema(self._db_path)

        # Model
        self.seen_delivery_ids: set[str] = set()
        self.ring_count: int = 0

        # Doorbell shim — count rings via a mutable list to avoid closure rebind.
        self._rings: list[int] = []
        self._doorbell_patcher = patch.object(_db._doorbell, "ring", side_effect=lambda: self._rings.append(1))
        self._doorbell_patcher.start()

    def teardown(self) -> None:
        self._doorbell_patcher.stop()
        import shutil

        shutil.rmtree(self._tmpdir, ignore_errors=True)

    # ------------------------------------------------------------------
    # Rules: staging
    # ------------------------------------------------------------------

    @rule(target=pending, ev=event_insert_strategy())
    def stage_fresh(self, ev: EventInsert) -> EventInsert:
        """Add a brand-new event (unique delivery_id) to the pending bundle."""
        return ev

    @rule(target=pending, dup=consumes(pending))
    def stage_duplicate(self, dup: EventInsert) -> EventInsert:
        """Re-stage an existing event so emit_batch sees it as a no-op."""
        return dup

    # ------------------------------------------------------------------
    # Rules: flushing
    # ------------------------------------------------------------------

    @rule(events=st.lists(pending, max_size=8))
    def flush_batch(self, events: list[EventInsert]) -> None:
        """Call emit_batch and verify returned count + doorbell behaviour."""
        new_ids = {ev.delivery_id for ev in events} - self.seen_delivery_ids
        expected_inserted = len(new_ids)

        rings_before = len(self._rings)
        result = emit_batch(events, db_path=self._db_path)

        assert result == expected_inserted, (
            f"emit_batch returned {result} but model expected {expected_inserted}; "
            f"new_ids={new_ids}, seen={self.seen_delivery_ids}"
        )

        rings_after = len(self._rings)
        expected_rings = 1 if expected_inserted > 0 else 0
        assert rings_after - rings_before == expected_rings, (
            f"doorbell rang {rings_after - rings_before} times; expected {expected_rings}"
        )

        # Advance model
        self.seen_delivery_ids |= new_ids
        self.ring_count += expected_rings

    @rule(events=st.lists(pending, min_size=2, max_size=4))
    def crash_mid_batch(self, events: list[EventInsert]) -> None:
        """Simulate a mid-batch exception and verify full rollback.

        Monkeypatches _db.insert_event to raise on its second call within
        this rule invocation, then verifies that no new rows were committed
        and the doorbell was not rung. min_size=2 ensures a second call
        always occurs so the crash is genuinely mid-batch.
        """
        ids_before = set(self.seen_delivery_ids)
        rings_before = len(self._rings)

        call_counter: list[int] = []
        original_insert_event = _db.insert_event

        def _faulty_insert(conn: Any, event: Any, *, commit: bool = True) -> bool:
            call_counter.append(1)
            if len(call_counter) >= 2:
                raise RuntimeError("synthetic mid-batch failure")
            return original_insert_event(conn, event, commit=commit)

        with patch.object(_db, "insert_event", side_effect=_faulty_insert), contextlib.suppress(Exception):
            emit_batch(events, db_path=self._db_path)

        # Model must be unchanged
        assert self.seen_delivery_ids == ids_before, "crash_mid_batch must not mutate seen_delivery_ids"
        assert len(self._rings) == rings_before, "doorbell must not ring after a mid-batch crash"

    # ------------------------------------------------------------------
    # Invariant
    # ------------------------------------------------------------------

    @invariant()
    def db_row_count_matches_model(self) -> None:
        """The live DB row count must always equal len(seen_delivery_ids)."""
        if not hasattr(self, "_db_path"):
            return  # setup not yet called
        conn = sqlite3.connect(str(self._db_path))
        try:
            db_count: int = conn.execute("SELECT COUNT(*) FROM events").fetchone()[0]
        finally:
            conn.close()
        assert db_count == len(self.seen_delivery_ids), (
            f"DB has {db_count} rows but model tracks {len(self.seen_delivery_ids)} ids"
        )


EmitBatchMachine.TestCase.settings = settings(
    max_examples=40,
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.large_base_example],
)

# Expose to pytest auto-discovery.
TestEmitBatchMachine = EmitBatchMachine.TestCase
